### ISSUE TITLE
hardware fuses?

### ISSUE THREAD

**Issue by iperry** [Riscure/RHme-2015#1]
Hi! I noticed this after the contest concluded but it seems pretty fun so far working through it on my own.

Question: on the original contest hardware, were any of the hardware fuses set? Were eeprom and/or flash program memory protected using any hardware features? Could contestants for example dump flash or eeprom contents using conventional AVR tools?

**Comment by RamiroPareja** [comment]
Hi, 

I am glad you enjoy the challenge.

During the contest, all the protection fuses were properly set in the provided targets so dumping the code was not an option. Otherwise, it would be too easy!
